2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Configure stats pid to 19452
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\cosmi\.config\wandb\settings
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Loading settings from C:\MyDocuments\Dizertatie\segments\wandb_visualization\no_overlap\wandb\settings
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'test_mode_visualization.py', 'program': 'C:\\MyDocuments\\Dizertatie\\segments\\wandb_visualization\\no_overlap\\test_mode_visualization.py'}
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:_log_setup():507] Logging user logs to C:\MyDocuments\Dizertatie\segments\wandb_visualization\no_overlap\wandb\run-20230407_135839-mhu3h0vs\logs\debug.log
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:_log_setup():508] Logging internal logs to C:\MyDocuments\Dizertatie\segments\wandb_visualization\no_overlap\wandb\run-20230407_135839-mhu3h0vs\logs\debug-internal.log
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:init():547] calling init triggers
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:init():595] starting backend
2023-04-07 13:58:39,478 INFO    MainThread:19452 [wandb_init.py:init():599] setting up manager
2023-04-07 13:58:39,494 INFO    MainThread:19452 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-07 13:58:39,506 INFO    MainThread:19452 [wandb_init.py:init():605] backend started and connected
2023-04-07 13:58:39,514 INFO    MainThread:19452 [wandb_init.py:init():695] updated telemetry
2023-04-07 13:58:39,522 INFO    MainThread:19452 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-07 13:58:39,992 INFO    MainThread:19452 [wandb_run.py:_on_init():2176] communicating current version
2023-04-07 13:58:40,179 INFO    MainThread:19452 [wandb_run.py:_on_init():2185] got version response 
2023-04-07 13:58:40,179 INFO    MainThread:19452 [wandb_init.py:init():782] starting run threads in backend
2023-04-07 13:58:41,448 INFO    MainThread:19452 [wandb_run.py:_console_start():2157] atexit reg
2023-04-07 13:58:41,448 INFO    MainThread:19452 [wandb_run.py:_redirect():2012] redirect: SettingsConsole.WRAP_RAW
2023-04-07 13:58:41,448 INFO    MainThread:19452 [wandb_run.py:_redirect():2077] Wrapping output streams.
2023-04-07 13:58:41,448 INFO    MainThread:19452 [wandb_run.py:_redirect():2102] Redirects installed.
2023-04-07 13:58:41,448 INFO    MainThread:19452 [wandb_init.py:init():824] run started, returning control to user process
2023-04-07 13:59:04,906 ERROR   MainThread:19452 [util.py:get_module():241] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\util.py", line 203, in import_module_lazy
    return sys.modules[name]
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\util.py", line 236, in get_module
    return import_module_lazy(name)
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\util.py", line 205, in import_module_lazy
    module_spec = importlib.util.find_spec(name)
  File "C:\Python310\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plotly'
2023-04-07 13:59:12,853 WARNING MsgRouterThr:19452 [router.py:message_loop():77] message_loop has been closed
