Predicted pos:  [0.414] actual pos:  [0.414]
Predicted pos:  [0.414] actual pos:  [0.414]
Predicted pos:  [0.4132] actual pos:  [0.414]
Predicted pos:  [0.4168] actual pos:  [0.414]
Predicted pos:  [0.414] actual pos:  [0.414]
Predicted pos:  [0.414] actual pos:  [0.414]
Predicted pos:  [0.4296] actual pos:  [0.432]
Predicted pos:  [0.4304] actual pos:  [0.432]
Predicted pos:  [0.4292] actual pos:  [0.432]
Predicted pos:  [0.4272] actual pos:  [0.432]
Predicted pos:  [0.4248] actual pos:  [0.432]
Predicted pos:  [0.4276] actual pos:  [0.432]
Predicted pos:  [0.4284] actual pos:  [0.432]
Predicted pos:  [0.4844] actual pos:  [0.468]
Predicted pos:  [0.5108] actual pos:  [0.468]
Predicted pos:  [0.4936] actual pos:  [0.468]
Predicted pos:  [0.496] actual pos:  [0.468]
Predicted pos:  [0.4948] actual pos:  [0.468]
Predicted pos:  [0.4964] actual pos:  [0.468]
Predicted pos:  [0.4944] actual pos:  [0.468]
Error(MSE) 0.0002947
Traceback (most recent call last):
  File "C:\MyDocuments\Dizertatie\segments\wandb_visualization\no_overlap\test_mode_visualization.py", line 111, in <module>
    table = wandb_config.Table(data=mse, columns=["mse_test"])
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\data_types.py", line 285, in __init__
    self._init_from_list(data, columns, optional, dtype)
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\data_types.py", line 310, in _init_from_list
    self.add_data(*row)
  File "C:\MyDocuments\Dizertatie\segments\venv\lib\site-packages\wandb\data_types.py", line 461, in add_data
    raise ValueError(
ValueError: This table expects 1 columns: ['mse_test'], found 9