wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0018s vs `on_train_batch_end` time: 0.0036s). Check your callbacks.
Epoch 1/10
101/173 [================>.............] - ETA: 0s - loss: 1.9611 - mae: 0.2804 - mse: 0.0907

173/173 [==============================] - ETA: 0s - loss: 1.6724 - mae: 0.2060 - mse: 0.0585
173/173 [==============================] - 3s 12ms/step - loss: 1.6724 - mae: 0.2060 - mse: 0.0585 - val_loss: 1.0572 - val_mae: 0.0807 - val_mse: 0.0081 - lr: 0.0010
Epoch 2/10
168/173 [============================>.] - ETA: 0s - loss: 0.7333 - mae: 0.0752 - mse: 0.0070
Traceback (most recent call last):
  File "C:\MyDocuments\Disertatie\segments\wandb_visualization\severity\wrapper_test_and_train.py", line 271, in <module>
    train_ANN()
  File "C:\MyDocuments\Disertatie\segments\wandb_visualization\severity\wrapper_test_and_train.py", line 129, in train_ANN
    train_models_and_save(n_members,data,test_size,train_group, epochs, batch_size, learning_rate,optimizer,hidden_layer_size,patience,monitor)
  File "C:\MyDocuments\Disertatie\segments\wandb_visualization\severity\test_and_train.py", line 31, in train_models_and_save
    network, history = train_model_sweep(build_nn_baseline(), x_train,
  File "C:\MyDocuments\Disertatie\segments\model_training\overlap\model_generating_RNN.py", line 119, in train_model_sweep
    history = network.fit(x_train, y_train, epochs=epochs, batch_size = batch_size, validation_data=(x_test, y_test),
  File "C:\Users\cosmi\AppData\Roaming\Python\Python39\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\cosmi\AppData\Roaming\Python\Python39\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\cosmi\AppData\Roaming\Python\Python39\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\engine\training.py", line 1624, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\callbacks.py", line 448, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\cosmi\AppData\Roaming\Python\Python39\site-packages\wandb\integration\keras\keras.py", line 630, in on_epoch_end
    self._save_model_as_artifact(epoch)
  File "C:\Users\cosmi\AppData\Roaming\Python\Python39\site-packages\wandb\integration\keras\keras.py", line 1032, in _save_model_as_artifact
    self.model.save(self.filepath[:-3], overwrite=True, save_format="tf")
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\engine\training.py", line 2698, in save
    save.save_model(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\saving\save.py", line 166, in save_model
    saved_model_save.save(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\saving\saved_model\save.py", line 97, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 1268, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 1441, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 1394, in _build_meta_graph_impl
    saveable_view = _SaveableView(augmented_graph_view, options)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 264, in __init__
    checkpoint_util.objects_ids_and_slot_variables_and_paths(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\util.py", line 441, in objects_ids_and_slot_variables_and_paths
    trackable_objects, node_paths = graph_view.breadth_first_traversal()
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 124, in breadth_first_traversal
    return self._breadth_first_traversal()
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 141, in _breadth_first_traversal
    super(_AugmentedGraphView, self)._breadth_first_traversal())
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 128, in _breadth_first_traversal
    return super(ObjectGraphView, self)._descendants_with_paths()
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\trackable_view.py", line 111, in _descendants_with_paths
    for name, dependency in self.children(current_trackable).items():
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 97, in children
    for name, ref in self.list_children(obj, **kwargs):
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\saved_model\save.py", line 175, in list_children
    for name, child in super(_AugmentedGraphView, self).list_children(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 75, in list_children
    for name, ref in super(ObjectGraphView,
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\checkpoint\trackable_view.py", line 84, in children
    for name, ref in obj._trackable_children(save_type, **kwargs).items():
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 1192, in _trackable_children
    enumerate(self._list_all_concrete_functions_for_serialization())}
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 1165, in _list_all_concrete_functions_for_serialization
    concrete_functions = self._list_all_concrete_functions()
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 1147, in _list_all_concrete_functions
    self.get_concrete_function()
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 1239, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 1219, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\function.py", line 2523, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\function.py", line 2760, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\function.py", line 2670, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1247, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\eager\def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1222, in autograph_handler
    return autograph.converted_call(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 352, in converted_call
    return converted_call(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "C:\Users\cosmi\AppData\Local\Temp\__autograph_generated_filejo33t2sv.py", line 14, in tf___loss_for_variable
    regularization = ag__.converted_call(ag__.ld(regularizer), (ag__.ld(v),), None, fscope)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 459, in _call_unconverted
    return f(*args)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\keras\regularizers.py", line 320, in __call__
    return 2.0 * self.l2 * tf.nn.l2_loss(x)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1442, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1767, in _mul_dispatch
    return multiply(x, y, name=name)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\util\dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\ops\math_ops.py", line 529, in multiply
    return gen_math_ops.mul(x, y, name)
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6588, in mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\func_graph.py", line 735, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
    ret = Operation(
  File "C:\Users\cosmi\anaconda3\envs\tf2.12\lib\site-packages\tensorflow\python\framework\ops.py", line 2118, in __init__
    self.traceback._stacklevel += 1  # pylint: disable=protected-access
173/173 [==============================] - 2s 12ms/step - loss: 0.7270 - mae: 0.0751 - mse: 0.0069 - val_loss: 0.4545 - val_mae: 0.0673 - val_mse: 0.0055 - lr: 0.0010
Epoch 3/10
170/173 [============================>.] - ETA: 0s - loss: 0.2840 - mae: 0.0666 - mse: 0.0054